### ISSUE TITLE
Не запускается приложение

### ISSUE THREAD

**Issue by alexey-olfert** [alexey-olfert/homework3-1#1]
**Описание**
После выполнения команды `docker-compose up` приложение не запускается командой `java -jar db-api.jar`, показывая ошибку.

**Шаги**
1. Создал новый Java проект в Idea.
2. Добавил файл application.properties со следующим содержанием:
```
spring.datasourse.url=jdbc:postgresql://8080/postgres
spring.datasourse.username=postgres
spring.datasourse.password=example
``` 
3. Добавил файл docker-compose.yml со следующим содержанием:
```
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
4. Запустил в терминале команду `docker-compose up`.
5. На следующей вкладке запустил команду `java -jar db-api.jar`

**Ожидаемый результат**
JSON с картами.

**Фактический результат**
Ошибка запуска:
```
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
        If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
        If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

```
@coursar @ArRomanov

**Comment by coursar** [comment]
Property `spring.datasourse.url` должно содержать url с именем/ip хоста и порт, т.е.: `spring.datasourse.url=jdbc:postgresql://localhost:5432/postgres`.

И почему вы пишите 8080? PostgreSQL по умолчанию работает на порту 5432 и его же надо экспортировать:

```yml
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
```

adminer вам вообще не нужен, зато нужны переменные окружения для PostgreSQL, которые выставляют, как минимум, пользователя и базу.

**Comment by alexey-olfert** [comment]
[Здесь](https://hub.docker.com/_/postgres) говорится, как я понял, что если не назначать переменные пользователя и пароля, то будут использоваться дефолтные значения - postgres/example. Их нужно поменять?

**Comment by alexey-olfert** [comment]
Как должны выглядеть переменные со значениями? Так?
```
POSTGRES_PASSWORD: qwerty123
POSTGRES_USER: alexey
POSTGRES_DB: postgres
```

**Comment by coursar** [comment]
```yml
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
```

**Comment by alexey-olfert** [comment]
Изменил docker-compose.yml:
```
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_USER=app
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
```
Изменил application.properties:
```
spring.datasourse.url=jdbc:postgresql://localhost:5432/app
spring.datasourse.username=app
spring.datasourse.password=qwerty123
```
Приложение всё ещё не запускается:
```
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
        If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
        If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
```
